### ISSUE TITLE
breadcrumbs

### ISSUE THREAD

**Issue by bbigras** [thomasluquet/emacs-can-do-that#10]
`(setq lsp-headerline-breadcrumb-enable t)`

and track https://github.com/emacs-lsp/lsp-mode/issues/1823

**Comment by thomasluquet** [comment]
Is it realy an issue ?
How can i help you to fix it ?

**Comment by bbigras** [comment]
I thought that "04 | Breadcrumbs" could mention that lsp-mode has breadcrumbs support.

**Comment by thomas-louvigne** [comment]
Good idea, why you don't send a PR ?
-- 
Thomas Luquet <http://fabrique-etudiante.fr/>
Mail : thomas@luquet.net
